USE [master]
GO

/****** Object:  Database [projectTax]    Script Date: 4/25/2017 10:03:50 PM ******/
CREATE DATABASE [projectTax]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projectTax', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\projectTax.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'projectTax_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\projectTax_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [projectTax] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projectTax].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projectTax] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projectTax] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projectTax] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projectTax] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projectTax] SET ARITHABORT OFF 
GO

ALTER DATABASE [projectTax] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projectTax] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projectTax] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projectTax] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projectTax] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projectTax] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projectTax] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projectTax] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projectTax] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projectTax] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projectTax] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projectTax] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projectTax] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projectTax] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projectTax] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projectTax] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projectTax] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projectTax] SET RECOVERY FULL 
GO

ALTER DATABASE [projectTax] SET  MULTI_USER 
GO

ALTER DATABASE [projectTax] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projectTax] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projectTax] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projectTax] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [projectTax] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projectTax] SET  READ_WRITE 
GO

